$ErrorActionPreference = "Stop"

# This plan was generated by recovery_mapper.ps1
# REVIEW THIS FILE BEFORE RUNNING.

# Repo root: C:\Users\User\Desktop\Compliance\Compliance

# 1) Create safety backup (copy, not move)
New-Item -ItemType Directory -Force "C:\Users\User\Desktop\Compliance\Compliance\_SAFETY_BACKUP_20260205_134036" | Out-Null
Write-Host "Creating safety backup..."
robocopy "C:\Users\User\Desktop\Compliance\Compliance" "C:\Users\User\Desktop\Compliance\Compliance\_SAFETY_BACKUP_20260205_134036" /E /NFL /NDL /NJH /NJS /NP | Out-Null
Write-Host "âœ… Safety backup created." -ForegroundColor Green

# 2) Move any nested repo candidates into _RECOVERY_INBOX (non-destructive to top-level)
New-Item -ItemType Directory -Force "C:\Users\User\Desktop\Compliance\Compliance\_RECOVERY_INBOX" | Out-Null

Write-Host "`nâœ… Done moving nested repos into _RECOVERY_INBOX." -ForegroundColor Green
Write-Host "Next step: we will selectively merge folders back into repo root (apps/db/scripts/public) once inbox is clean." -ForegroundColor Yellow
