@'
/**
 * P2-03 — SOS schema module (single source of truth)
 * DO NOT EDIT column arrays/order.
 */

export const SOS_COLUMNS = {
  header: [
    "FilingEntityName",
    "FilingEntityID",
    "Date",
  ],
  contributions: [
    "Actions",
    "ExternalContributionID",
    "ContributionDate",
    "ContributionAmount",
    "ContributionType",
    "ElectionType",
    "ContributorType",
    "ExternalContributorID",
    "FilingEntityID",
    "ContributorOrganizationName",
    "ContributorFirstName",
    "ContributorMiddleName",
    "ContributorLastName",
    "ContributorSuffix",
    "ContributorAddressLine1",
    "ContributorAddressLine2",
    "ContributorCity",
    "ContributorState",
    "ContributorZipCode",
    "ContributorEmployer",
    "ContributorOccupation",
    "ContributorOccupationOther",
    "ContributionDescription",
  ],
  contributionReturns: [
    "Actions",
    "ExternalReturnContributionID",
    "ExternalContributionID",
    "ContributionReturnDate",
    "ContributionReturnAmount",
    "ContributionReturnReason",
  ],
  expenditures: [
    "Actions",
    "ExternalExpenditureID",
    "ExpenditureDate",
    "ExpenditureAmount",
    "ExpenditureType",
    "ElectionType",
    "ExpenditureCategory",
    "ExpenditureCategoryOtherDescription",
    "PayeeType",
    "ExternalPayeeID",
    "FilingEntityID",
    "PayeeOrganizationName",
    "PayeeFirstName",
    "PayeeMiddleName",
    "PayeeLastName",
    "PayeeSuffix",
    "PayeeAddressLine1",
    "PayeeAddressLine2",
    "PayeeCity",
    "PayeeState",
    "PayeeZipCode",
    "ExpenditureDescription",
  ],
  expenditureReturns: [
    "Actions",
    "ExternalReturnExpenditureID",
    "ExternalExpenditureID",
    "ExpenditureReturnDate",
    "ExpenditureReturnAmount",
    "ExpenditureReturnReason",
  ],
} as const;
'@ | Set-Content -Encoding UTF8 "apps/campaign_compliance/lib/sos-schema.ts"
